export const descriptionList: string[]=[
    "⚡ &nbsp; 80% reduction on electricity bill",
    "💸 &nbsp; 35% cheaper than rooftop solar",
    "⏱ &nbsp; Instant connection",
    "🌆 &nbsp; No need for rooftop",
    "🔄 &nbsp; 4.5 years payback",
    "&nbsp; 25 years useful life",
    "🌱  &nbsp; 100% renewable",
]



export const GetOfferCardData:{
    is_premium:boolean,
    title:string,
    desc:string,
    feature:string[]
}[]=[{
    is_premium:false,
    title:"Standard Offer",
    desc:"You will not need anything else to get the offer",
    feature:["Instant Calculation","Answer 4 Questions","85% Accurate"]
},{
    is_premium:true,
    title:"Personalised Offer",
    desc:"You will need your latest electricity bill to get the offer",
    feature:["Instant Calculation","Answer 4 Questions","100% Accurate"]
}]


export const HowItWorksList: string[]=[
    "Neos becomes your retailer and uses the grid system to transport the electricity generated by your solar panels into your home. ",
    "During solar production hours, you will pay €0.00 for the energy you consume.",
    "If there’s excess production, Neos will sell 100% of the excess to the electricity market.",
    "Outside of solar production hours you will pay the market price of electricity, with a margin of €0.01 per KWh. ",
    "You will need to pay tolls and costs associated with using the grid, estimated at €0.02 per KWh. ",
    "If you decide you do not want Neos as your retailer, there’s no commitment to stay with us, and you can choose another retailer at any point. ",
    "If you choose another retailer, we will send you every month the revenues generated by selling your solar energy into the electricity market, which is equivalent to the savings you would obtain if you were still with Neos. ",
]

export const CompareOfferList: string[]=[
    "cheaper than rooftop solar panels",
    "more energy production per panel compared to rooftop solar panels",
    "savings compared to traditional utility providers",
    "less carbon intensive than traditional utility providers"
]